### ISSUE TITLE
dealing with previous transactions logs persistence

### ISSUE THREAD

**Issue by 3omer** [noebs/web#4]
I'm thinking of a better way to handle persisting transactions logs.
I suggest to handle this by an angular-service. It's a lot cleaner to use this single interface across all the app + the components don't have to worry about serializing/parsing into/from `localStorage`, the service will hide this.

-  components that initiate transactions can call something like `transLogs.add(transactoinRecord)` to log response. 
-  The previous transactions page can call something like `transLogs.all()`.

If possible, we can make the service accepts an argument of type `transactionRecord`.
```javascript
interface transactionRecord = {
type: 'E-15' | `BillEnqeuiry` | 'BalanceInquiry' | ... ,
status: 'success' | 'failure',
tranDateTime: string,
... others
}
```

**Comment by adonese** [comment]
Perfect! Go ahead with that!
